<template>
	<Fixed>
		<iframe
			src="https://docs.google.com/forms/d/e/1FAIpQLScHIrrdLHayB8kvMgS_tQhxLZXNacMnwxNiOD0vfYDODDT8Wg/viewform?embedded=true"
			class="w-full"
			height="2000"
			frameborder="0"
			marginheight="0"
			marginwidth="0"
		>
			Loading…
		</iframe>
	</Fixed>
</template>
